CREATE TABLE `employees` (
  `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL);

CREATE TABLE `categories` (
    `id` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL);


CREATE TABLE `products` (
    `id` INT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(45) NOT NULL,
    `category_id` INT NOT NULL);